version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
  pre_build:
    commands:
      - npm install -g newman
  build:
    commands:
      - newman run postman/APITest.postman_collection.json -e postman/wso2-apim-AWS-mitrai.postman_environment.json --insecure
  post_build:
    commands:
      - echo Build completed on `date`
